name: Refactor

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'Test' ]
    types:
      - completed

permissions:
  contents: read

jobs:
  refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint

      - name: Run Rector
        run: vendor/bin/rector
        
      - name: Commit Changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated code refactor with Pint and Refacto"
          git push
