name: Static Analysis

on: ['push', 'pull_request']

jobs:
  test:
    name: Tests

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }} on ${{ matrix.os }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run Pest Tests
        run: ./vendor/bin/pest
